[package]
name = "transits"
version = "0.1.0"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "*"
rocket_codegen = "*"
serde_derive = "1.0"
serde = "*"
serde_json = "*"
glob = "*"
gnuplot = "0.0.29"
