# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Transits Documentation
tagline:             'A VARTOOLS pipeline'
description:         'A pipefile for <a target="_new" href="https://www.astro.princeton.edu/~jhartman/vartools.html">VARTOOLS</a>, the astronomical light curve program'
url:                 https://github.com/llamicron/transits/
baseurl:             'https://llamicron.github.io/transits/'
# paginate:            5

# About/contact
author:
  name:              Luke Sweeney
  url:               https://github.com/llamicron
  email:             llamicron@gmail.com

# Custom vars
version:             0.1.0

plugins: []
