# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Transits Documentation
tagline:             'A VARTOOLS pipeline'
description:         'A pipefile for <a target="_new" href="https://www.astro.princeton.edu/~jhartman/vartools.html">VARTOOLS</a>, the astronomical light curve program'
url:                 https://llamicron.github.io/transits/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             0.1.0

plugins: [jekyll-paginate]
